states 9
CHECK.0
GETN
GET|
GETD
RESET
BACK
CHECKDONE
ACCEPT +
REJECT -
alphabet 4 | 1 X F
CHECK.0 1 RESET 1 L
CHECK.0 | REJECT | L
GETN 1 GET| F R
GETN | CHECKDONE | R
GET| 1 GET| 1 R
GET| X GET| X R
GET| | GETD | R
GETD 1 BACK X L
GETD X GETD X R
GETD _ REJECT _ L
RESET 1 GETN 1 N
RESET F RESET 1 L
RESET X RESET X L
RESET | RESET | L
BACK X BACK X L
BACK 1 BACK 1 L
BACK F GETN F R
BACK | BACK | L
CHECKDONE X CHECKDONE X R
CHECKDONE 1 RESET 1 L
CHECKDONE _ ACCEPT _ L